### PR TITLE
Separate out the compose call.

### PR DESCRIPTION
**Pull request by doug**
Useful for when uses are not changing the Wares after composing so it doesn't have to compose on every call to ServeHTTP.

### CODE REVIEW

**Comment by mholt** [comment]
This is a related idea to #8 - just FYI.

**Comment by doug** [comment]
Totally agree, apologies as I should have read through the previous issues first before making a PR. Though now reading both, I still think this implementation has merit. Surfacing the compile behavior publicly `middleware.Handler()` gives the user of the library more control, while being totally backwards compatible for anyone already using the library with the expected behavior of recomposing ever time. It is explicit and less automagical, which I really appreciate as a developer.

**Comment by mholt** [comment]
I think this PR is an improvement; you don't need to apologize. @carbocation doesn't need to wait for me to review #8 either (just in case that wasn't clear).

I still feel like the empty handler is silly; there's a clever way to get rid of it, but I haven't the time right now to figure it out.

Anyway, +1 on this. :+1:

**Comment by carbocation** [comment]
Am very busy until Sunday, but am looking forward to taking a look. Especially if the changes are less intrusive than my 'compiled' branch, I will happily incorporate this or a derivative into master.

**Pull request merged**
